# Generated by Django 3.0 on 2021-05-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'db_table': 'Aprendiz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Asistencia', models.DateField(verbose_name='Fecha de Asistencia')),
                ('Notes', models.CharField(max_length=70, null=True, verbose_name='Anotaciones')),
                ('Aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Aprendiz', verbose_name='Aprendiz')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_T_Document', models.CharField(max_length=10, verbose_name='Nombre tipo de Documento')),
                ('acronym_D', models.CharField(max_length=3, null=True, verbose_name='Siglas de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado_Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_E_Asis', models.CharField(max_length=20, verbose_name='Nombre Estado de Asistencia')),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'db_table': 'Estado de Asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Group', models.CharField(max_length=30, verbose_name='Nombre Grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_J', models.CharField(max_length=30, verbose_name='Nombre Jornada')),
                ('acronym_J', models.CharField(max_length=10, verbose_name='Siglas Jornada')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'Jornada',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_P', models.CharField(max_length=50, verbose_name='Nombre de Programa')),
                ('acronym_P', models.CharField(max_length=10, null=True, verbose_name='Siglas del Programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'Programa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_R', models.CharField(max_length=20, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_S', models.CharField(max_length=20, verbose_name='Nombre de Sede')),
                ('adress_S', models.CharField(max_length=30, null=True, verbose_name='Dirección de Sede')),
                ('city_S', models.CharField(max_length=20, verbose_name='Ciudad de Sede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Tri', models.CharField(max_length=20, verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'db_table': 'Trimestre',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Documento', models.CharField(max_length=25, unique=True, verbose_name='Numero de documento')),
                ('first_name', models.CharField(max_length=40, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(max_length=40, null=True, verbose_name='Segundo Nombre')),
                ('F_last_name', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('S_last_name', models.CharField(max_length=45, null=True, verbose_name='Segundo Apellido')),
                ('Phone_number', models.CharField(max_length=15, verbose_name='Telefono Celular')),
                ('Tel_number', models.CharField(max_length=40, null=True, verbose_name='Telefono Fijo')),
                ('Person_mail', models.CharField(max_length=45, null=True, verbose_name='Correo Electronico Personal')),
                ('Inst_mail', models.CharField(max_length=50, verbose_name='Correo Electronico Institucional')),
                ('Date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Documento', verbose_name='Tipo de documento')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=25, verbose_name='Contraseña')),
                ('Documento_I', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoDocumentoI', to='Sirac_users.Usuario', to_field='Documento', verbose_name='Tipo de Documento')),
                ('N_Documento_I', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NDocumentoI', to='Sirac_users.Usuario', to_field='N_Documento', verbose_name='Numero de Documento')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'db_table': 'Instructor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_F', models.IntegerField(unique=True, verbose_name='Numero de Ficha')),
                ('Jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Jornada', verbose_name='Jornada')),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Programa', verbose_name='Programa')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'db_table': 'Ficha',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Excusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Excusa', models.CharField(max_length=25, verbose_name='Nombre de Excusa')),
                ('Date_Excusa', models.DateField(verbose_name='Fecha de Excusa')),
                ('Description_Ex', models.CharField(max_length=50, null=True, verbose_name='Descripcion Excusa')),
                ('Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Asistencia', verbose_name='Asistencia registrada')),
            ],
            options={
                'verbose_name': 'Excusa',
                'verbose_name_plural': 'Excusas',
                'db_table': 'Excusa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_E', models.CharField(max_length=50, verbose_name='Nombre Especialidad')),
                ('Days_E', models.CharField(max_length=60, verbose_name='Dias Especialidad')),
                ('Time_Begining', models.TimeField(verbose_name='Hora de inico')),
                ('Time_Ending', models.TimeField(verbose_name='Hora final')),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Instructor', verbose_name='Instructor Encargado')),
                ('N_Ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Ficha', verbose_name='Numero de Ficha')),
                ('Trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Trimestre', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidad',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Estado_Asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Estado_Asistencia', verbose_name='Estado de Asistencia'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='Ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Ficha', to_field='number_F', verbose_name='Numero de Ficha'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='Grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='N_Documento_A',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NDocumentoA', to='Sirac_users.Usuario', to_field='N_Documento', verbose_name='Numero de documento'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='T_Documento_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoDocumentoA', to='Sirac_users.Usuario', to_field='Documento', verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='Adminitrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password_Adm', models.CharField(max_length=25, verbose_name='Contraseña')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
                'ordering': ['id'],
            },
        ),
    ]
