# Generated by Django 3.0 on 2021-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0005_auto_20210523_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminitrador',
            name='Username',
            field=models.CharField(default=12, max_length=10, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
    ]
