# Generated by Django 3.0 on 2021-05-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0006_adminitrador_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendiz',
            name='T_Documento_A',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='Documento_I',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='N_Documento_I',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Usuario', to_field='N_Documento', verbose_name='Numero de Documento'),
        ),
    ]
