# Generated by Django 3.0 on 2021-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0007_auto_20210526_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='excusa',
            name='Soporte_Excusa',
            field=models.FileField(default=12, upload_to='', verbose_name='Soporte de la excusa'),
            preserve_default=False,
        ),
    ]
