# Generated by Django 3.0 on 2021-05-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0009_auto_20210526_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='adress_S',
            new_name='address_S',
        ),
    ]
