# Generated by Django 3.0 on 2021-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0011_auto_20210526_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='acronym_D',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Siglas de Documento'),
        ),
    ]
