# Generated by Django 3.0 on 2021-05-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0012_auto_20210526_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sirac_users.Documento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
