# Generated by Django 3.2.3 on 2021-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0014_auto_20210528_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Date',
            field=models.CharField(max_length=30, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
