# Generated by Django 3.2.3 on 2021-12-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sirac_users', '0016_auto_20211207_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Fotos/', verbose_name='Foto de perfil'),
        ),
    ]
